name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout
    - name: Set up JDK 1.11
      uses: actions/setup-java
      with:
        java-version: 1.11
    - name: Build with Gradle
      run: ./gradlew build
